name: Test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: [ "v0.9.1" ]

    steps:
      - uses: actions/checkout@v3
      - uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: ${{ matrix.neovim-version }}
      - name: Install Neovim plugins
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/nfnl-tests/start
          git clone https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/site/pack/nfnl-tests/start/plenary
          ln -s . ~/.local/share/nvim/site/pack/nfnl-tests/start/nfnl
      - name: Test with plenary / busted
        run: |
          ./script/test
